export const variants = {
  h1: {
    fontSmoothing: "antialiased",
    letterSpacing: "tracking-normal",
    fontSize: "text-5xl",
    fontWeight: "font-semibold",
    lineHeight: "leading-tight",
  },
  h2: {
    fontSmoothing: "antialiased",
    letterSpacing: "tracking-normal",
    fontSize: "text-4xl",
    fontWeight: "font-semibold",
    lineHeight: "leading-[1.3]",
  },
  h3: {
    fontSmoothing: "antialiased",
    letterSpacing: "tracking-normal",
    fontSize: "text-3xl",
    fontWeight: "font-semibold",
    lineHeight: "leading-snug",
  },
  h4: {
    fontSmoothing: "antialiased",
    letterSpacing: "tracking-normal",
    fontSize: "text-2xl",
    fontWeight: "font-semibold",
    lineHeight: "leading-snug",
  },
  h5: {
    fontSmoothing: "antialiased",
    letterSpacing: "tracking-normal",
    fontSize: "text-xl",
    fontWeight: "font-semibold",
    lineHeight: "leading-snug",
  },
  h6: {
    fontSmoothing: "antialiased",
    letterSpacing: "tracking-normal",
    fontSize: "text-base",
    fontWeight: "font-semibold",
    lineHeight: "leading-relaxed",
  },
  paragraph: {
    fontSmoothing: "antialiased",
    fontSize: "text-base",
    fontWeight: "font-light",
    lineHeight: "leading-relaxed",
  },
  span: {
    fontSmoothing: "antialiased",
    fontSize: "text-sm",
    fontWeight: "font-light",
    lineHeight: "leading-normal",
  },
}