import './globals.css'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { QueryClientProviders } from '@/components/TanstackQueryClient/QueryClientProviders'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProviders> 
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProviders>
      </body>
    </html>
  )
}
